# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(533, 299)
        font = QtGui.QFont()
        font.setPointSize(11)
        login.setFont(font)
        self.user_name_edit = QtWidgets.QLineEdit(login)
        self.user_name_edit.setGeometry(QtCore.QRect(150, 40, 311, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.user_name_edit.setFont(font)
        self.user_name_edit.setObjectName("user_name_edit")
        self.test_sel_rbutton = QtWidgets.QRadioButton(login)
        self.test_sel_rbutton.setGeometry(QtCore.QRect(340, 200, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.test_sel_rbutton.setFont(font)
        self.test_sel_rbutton.setObjectName("test_sel_rbutton")
        self.label = QtWidgets.QLabel(login)
        self.label.setGeometry(QtCore.QRect(60, 40, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.password_edit = QtWidgets.QLineEdit(login)
        self.password_edit.setGeometry(QtCore.QRect(150, 100, 311, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.password_edit.setFont(font)
        self.password_edit.setMaxLength(16)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.label_2 = QtWidgets.QLabel(login)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.login_button = QtWidgets.QPushButton(login)
        self.login_button.setGeometry(QtCore.QRect(170, 180, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.checkBox = QtWidgets.QCheckBox(login)
        self.checkBox.setGeometry(QtCore.QRect(340, 250, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "中云信安生产工具登录"))
        self.test_sel_rbutton.setText(_translate("login", "测试模式"))
        self.label.setText(_translate("login", "账号："))
        self.label_2.setText(_translate("login", "密码："))
        self.login_button.setText(_translate("login", "登录"))
        self.checkBox.setText(_translate("login", "新MES系统"))
