# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrderDialog(object):
    def setupUi(self, OrderDialog):
        OrderDialog.setObjectName("OrderDialog")
        OrderDialog.resize(938, 632)
        self.order_table_widget = QtWidgets.QTableWidget(OrderDialog)
        self.order_table_widget.setGeometry(QtCore.QRect(0, 0, 931, 451))
        self.order_table_widget.setAcceptDrops(True)
        self.order_table_widget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.order_table_widget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.order_table_widget.setProperty("showDropIndicator", False)
        self.order_table_widget.setDragDropOverwriteMode(False)
        self.order_table_widget.setAlternatingRowColors(False)
        self.order_table_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.order_table_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.order_table_widget.setShowGrid(False)
        self.order_table_widget.setGridStyle(QtCore.Qt.NoPen)
        self.order_table_widget.setWordWrap(False)
        self.order_table_widget.setCornerButtonEnabled(False)
        self.order_table_widget.setObjectName("order_table_widget")
        self.order_table_widget.setColumnCount(0)
        self.order_table_widget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.order_table_widget.setVerticalHeaderItem(0, item)
        self.order_table_widget.verticalHeader().setVisible(True)
        self.ok_btn = QtWidgets.QPushButton(OrderDialog)
        self.ok_btn.setGeometry(QtCore.QRect(220, 570, 131, 51))
        self.ok_btn.setObjectName("ok_btn")
        self.exit_btn = QtWidgets.QPushButton(OrderDialog)
        self.exit_btn.setGeometry(QtCore.QRect(430, 570, 141, 51))
        self.exit_btn.setObjectName("exit_btn")
        self.db_update_cbox = QtWidgets.QCheckBox(OrderDialog)
        self.db_update_cbox.setGeometry(QtCore.QRect(90, 460, 191, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.db_update_cbox.setFont(font)
        self.db_update_cbox.setChecked(True)
        self.db_update_cbox.setObjectName("db_update_cbox")
        self.scrip_update_cbox = QtWidgets.QCheckBox(OrderDialog)
        self.scrip_update_cbox.setGeometry(QtCore.QRect(90, 490, 211, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.scrip_update_cbox.setFont(font)
        self.scrip_update_cbox.setChecked(True)
        self.scrip_update_cbox.setObjectName("scrip_update_cbox")
        self.check_post_cbox = QtWidgets.QCheckBox(OrderDialog)
        self.check_post_cbox.setGeometry(QtCore.QRect(370, 460, 211, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.check_post_cbox.setFont(font)
        self.check_post_cbox.setChecked(True)
        self.check_post_cbox.setObjectName("check_post_cbox")
        self.mmpt_update_cbox = QtWidgets.QCheckBox(OrderDialog)
        self.mmpt_update_cbox.setGeometry(QtCore.QRect(370, 490, 211, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.mmpt_update_cbox.setFont(font)
        self.mmpt_update_cbox.setChecked(True)
        self.mmpt_update_cbox.setObjectName("mmpt_update_cbox")
        self.imei_uniq_cbox = QtWidgets.QCheckBox(OrderDialog)
        self.imei_uniq_cbox.setGeometry(QtCore.QRect(90, 520, 211, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.imei_uniq_cbox.setFont(font)
        self.imei_uniq_cbox.setChecked(True)
        self.imei_uniq_cbox.setObjectName("imei_uniq_cbox")
        self.repair_cbox = QtWidgets.QCheckBox(OrderDialog)
        self.repair_cbox.setGeometry(QtCore.QRect(630, 460, 141, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.repair_cbox.setFont(font)
        self.repair_cbox.setChecked(False)
        self.repair_cbox.setObjectName("repair_cbox")

        self.retranslateUi(OrderDialog)
        QtCore.QMetaObject.connectSlotsByName(OrderDialog)

    def retranslateUi(self, OrderDialog):
        _translate = QtCore.QCoreApplication.translate
        OrderDialog.setWindowTitle(_translate("OrderDialog", "订单选择"))
        self.ok_btn.setText(_translate("OrderDialog", "确认选择"))
        self.exit_btn.setText(_translate("OrderDialog", "退出"))
        self.db_update_cbox.setText(_translate("OrderDialog", "DB文件强制更新"))
        self.scrip_update_cbox.setText(_translate("OrderDialog", "脚本文件强制更新"))
        self.check_post_cbox.setText(_translate("OrderDialog", "强制检查MES上报结果"))
        self.mmpt_update_cbox.setText(_translate("OrderDialog", "MMPT工具强制更新"))
        self.imei_uniq_cbox.setText(_translate("OrderDialog", "强制检查IMEI唯一"))
        self.repair_cbox.setText(_translate("OrderDialog", "维修和清尾"))

