# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProductMainWindow(object):
    def setupUi(self, ProductMainWindow):
        ProductMainWindow.setObjectName("ProductMainWindow")
        ProductMainWindow.resize(1028, 768)
        self.centralwidget = QtWidgets.QWidget(ProductMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 461, 331))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(20, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(20, 285, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.product_ver_label = QtWidgets.QLabel(self.groupBox)
        self.product_ver_label.setGeometry(QtCore.QRect(116, 186, 311, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_ver_label.sizePolicy().hasHeightForWidth())
        self.product_ver_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.product_ver_label.setFont(font)
        self.product_ver_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.product_ver_label.setWordWrap(False)
        self.product_ver_label.setObjectName("product_ver_label")
        self.product_count_label = QtWidgets.QLabel(self.groupBox)
        self.product_count_label.setGeometry(QtCore.QRect(120, 280, 281, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.product_count_label.setFont(font)
        self.product_count_label.setObjectName("product_count_label")
        self.erp_material_id_label_xxx = QtWidgets.QLabel(self.groupBox)
        self.erp_material_id_label_xxx.setGeometry(QtCore.QRect(20, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.erp_material_id_label_xxx.setFont(font)
        self.erp_material_id_label_xxx.setObjectName("erp_material_id_label_xxx")
        self.erp_material_id_label = QtWidgets.QLabel(self.groupBox)
        self.erp_material_id_label.setGeometry(QtCore.QRect(115, 121, 241, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.erp_material_id_label.setFont(font)
        self.erp_material_id_label.setObjectName("erp_material_id_label")
        self.material_code_label_XX = QtWidgets.QLabel(self.groupBox)
        self.material_code_label_XX.setGeometry(QtCore.QRect(20, 150, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.material_code_label_XX.setFont(font)
        self.material_code_label_XX.setObjectName("material_code_label_XX")
        self.material_code_label = QtWidgets.QLabel(self.groupBox)
        self.material_code_label.setGeometry(QtCore.QRect(114, 151, 241, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.material_code_label.setFont(font)
        self.material_code_label.setObjectName("material_code_label")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(19, 28, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.tool_version_label = QtWidgets.QLabel(self.groupBox)
        self.tool_version_label.setGeometry(QtCore.QRect(117, 26, 281, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.tool_version_label.setFont(font)
        self.tool_version_label.setObjectName("tool_version_label")
        self.project_name_label = QtWidgets.QLabel(self.groupBox)
        self.project_name_label.setGeometry(QtCore.QRect(114, 90, 251, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.project_name_label.setFont(font)
        self.project_name_label.setObjectName("project_name_label")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.order_num_label = QtWidgets.QLabel(self.groupBox)
        self.order_num_label.setGeometry(QtCore.QRect(112, 54, 271, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.order_num_label.setFont(font)
        self.order_num_label.setObjectName("order_num_label")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(270, 60, 181, 141))
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 350, 461, 331))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(8, 122, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 161, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.station_type_label = QtWidgets.QLabel(self.groupBox_2)
        self.station_type_label.setGeometry(QtCore.QRect(100, 90, 291, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.station_type_label.setFont(font)
        self.station_type_label.setObjectName("station_type_label")
        self.station_flow_label = QtWidgets.QLabel(self.groupBox_2)
        self.station_flow_label.setGeometry(QtCore.QRect(109, 130, 321, 81))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.station_flow_label.setFont(font)
        self.station_flow_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.station_flow_label.setWordWrap(True)
        self.station_flow_label.setObjectName("station_flow_label")
        self.dc_address_label = QtWidgets.QLabel(self.groupBox_2)
        self.dc_address_label.setGeometry(QtCore.QRect(180, 250, 231, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.dc_address_label.setFont(font)
        self.dc_address_label.setObjectName("dc_address_label")
        self.cmw_addr_label = QtWidgets.QLabel(self.groupBox_2)
        self.cmw_addr_label.setGeometry(QtCore.QRect(130, 220, 291, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.cmw_addr_label.setFont(font)
        self.cmw_addr_label.setObjectName("cmw_addr_label")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(8, 27, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.station_num_label = QtWidgets.QLabel(self.groupBox_2)
        self.station_num_label.setGeometry(QtCore.QRect(110, 30, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.station_num_label.setFont(font)
        self.station_num_label.setObjectName("station_num_label")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.factory_mes_res_label = QtWidgets.QLabel(self.groupBox_2)
        self.factory_mes_res_label.setGeometry(QtCore.QRect(100, 60, 291, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.factory_mes_res_label.setFont(font)
        self.factory_mes_res_label.setObjectName("factory_mes_res_label")
        self.linenum_txt_label = QtWidgets.QLabel(self.groupBox_2)
        self.linenum_txt_label.setGeometry(QtCore.QRect(180, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.linenum_txt_label.setFont(font)
        self.linenum_txt_label.setObjectName("linenum_txt_label")
        self.line_num_label = QtWidgets.QLabel(self.groupBox_2)
        self.line_num_label.setGeometry(QtCore.QRect(280, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.line_num_label.setFont(font)
        self.line_num_label.setObjectName("line_num_label")
        self.product_info_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.product_info_gbox.setGeometry(QtCore.QRect(480, 10, 531, 231))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.product_info_gbox.setFont(font)
        self.product_info_gbox.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.product_info_gbox.setObjectName("product_info_gbox")
        self.label_6 = QtWidgets.QLabel(self.product_info_gbox)
        self.label_6.setGeometry(QtCore.QRect(13, 188, 111, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.res_bg_label = QtWidgets.QLabel(self.product_info_gbox)
        self.res_bg_label.setGeometry(QtCore.QRect(340, 20, 161, 121))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.res_bg_label.setFont(font)
        self.res_bg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.res_bg_label.setObjectName("res_bg_label")
        self.product_imei_lable = QtWidgets.QLabel(self.product_info_gbox)
        self.product_imei_lable.setGeometry(QtCore.QRect(120, 190, 211, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.product_imei_lable.setFont(font)
        self.product_imei_lable.setText("")
        self.product_imei_lable.setObjectName("product_imei_lable")
        self.elapsed_time_label = QtWidgets.QLabel(self.product_info_gbox)
        self.elapsed_time_label.setGeometry(QtCore.QRect(330, 150, 171, 61))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(18)
        self.elapsed_time_label.setFont(font)
        self.elapsed_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.elapsed_time_label.setObjectName("elapsed_time_label")
        self.label_7 = QtWidgets.QLabel(self.product_info_gbox)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(self.product_info_gbox)
        self.label_16.setGeometry(QtCore.QRect(10, 62, 111, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.success_total_label = QtWidgets.QLabel(self.product_info_gbox)
        self.success_total_label.setGeometry(QtCore.QRect(130, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.success_total_label.setFont(font)
        self.success_total_label.setObjectName("success_total_label")
        self.false_total_label = QtWidgets.QLabel(self.product_info_gbox)
        self.false_total_label.setGeometry(QtCore.QRect(130, 64, 71, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.false_total_label.setFont(font)
        self.false_total_label.setObjectName("false_total_label")
        self.label_18 = QtWidgets.QLabel(self.product_info_gbox)
        self.label_18.setGeometry(QtCore.QRect(30, 94, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.product_info_gbox)
        self.label_19.setGeometry(QtCore.QRect(180, 93, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.product_info_gbox)
        self.label_20.setGeometry(QtCore.QRect(30, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.product_info_gbox)
        self.label_21.setGeometry(QtCore.QRect(179, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lte_false_label = QtWidgets.QLabel(self.product_info_gbox)
        self.lte_false_label.setGeometry(QtCore.QRect(110, 94, 61, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lte_false_label.setFont(font)
        self.lte_false_label.setObjectName("lte_false_label")
        self.gsm_false_label = QtWidgets.QLabel(self.product_info_gbox)
        self.gsm_false_label.setGeometry(QtCore.QRect(270, 94, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.gsm_false_label.setFont(font)
        self.gsm_false_label.setObjectName("gsm_false_label")
        self.adc_false_label = QtWidgets.QLabel(self.product_info_gbox)
        self.adc_false_label.setGeometry(QtCore.QRect(110, 120, 51, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.adc_false_label.setFont(font)
        self.adc_false_label.setObjectName("adc_false_label")
        self.other_false_label = QtWidgets.QLabel(self.product_info_gbox)
        self.other_false_label.setGeometry(QtCore.QRect(271, 150, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.other_false_label.setFont(font)
        self.other_false_label.setObjectName("other_false_label")
        self.label_22 = QtWidgets.QLabel(self.product_info_gbox)
        self.label_22.setGeometry(QtCore.QRect(179, 120, 81, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.imei_false_label = QtWidgets.QLabel(self.product_info_gbox)
        self.imei_false_label.setGeometry(QtCore.QRect(270, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.imei_false_label.setFont(font)
        self.imei_false_label.setObjectName("imei_false_label")
        self.label_23 = QtWidgets.QLabel(self.product_info_gbox)
        self.label_23.setGeometry(QtCore.QRect(28, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.mes_false_label = QtWidgets.QLabel(self.product_info_gbox)
        self.mes_false_label.setGeometry(QtCore.QRect(112, 150, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.mes_false_label.setFont(font)
        self.mes_false_label.setObjectName("mes_false_label")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 250, 531, 461))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.imei_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.imei_edit.setGeometry(QtCore.QRect(120, 20, 391, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.imei_edit.setFont(font)
        self.imei_edit.setObjectName("imei_edit")
        self.product_info_text = QtWidgets.QTextBrowser(self.groupBox_4)
        self.product_info_text.setGeometry(QtCore.QRect(10, 80, 511, 381))
        self.product_info_text.setFocusPolicy(QtCore.Qt.NoFocus)
        self.product_info_text.setObjectName("product_info_text")
        ProductMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProductMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1028, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        ProductMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProductMainWindow)
        self.statusbar.setObjectName("statusbar")
        ProductMainWindow.setStatusBar(self.statusbar)
        self.lossset_config_action = QtWidgets.QAction(ProductMainWindow)
        self.lossset_config_action.setObjectName("lossset_config_action")
        self.action_2 = QtWidgets.QAction(ProductMainWindow)
        self.action_2.setObjectName("action_2")
        self.app_update = QtWidgets.QAction(ProductMainWindow)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.app_update.setFont(font)
        self.app_update.setObjectName("app_update")
        self.app_update_action = QtWidgets.QAction(ProductMainWindow)
        self.app_update_action.setObjectName("app_update_action")
        self.menu_2.addAction(self.app_update_action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(ProductMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ProductMainWindow)

    def retranslateUi(self, ProductMainWindow):
        _translate = QtCore.QCoreApplication.translate
        ProductMainWindow.setWindowTitle(_translate("ProductMainWindow", "中云信安生产工具"))
        self.groupBox.setTitle(_translate("ProductMainWindow", "订单信息"))
        self.label_13.setText(_translate("ProductMainWindow", "项目版本:"))
        self.label_14.setText(_translate("ProductMainWindow", "生产数量:"))
        self.product_ver_label.setText(_translate("ProductMainWindow", "XXXXXX"))
        self.product_count_label.setText(_translate("ProductMainWindow", "XXXXXX"))
        self.erp_material_id_label_xxx.setText(_translate("ProductMainWindow", "产品编码:"))
        self.erp_material_id_label.setText(_translate("ProductMainWindow", "XXXXXX"))
        self.material_code_label_XX.setText(_translate("ProductMainWindow", "产品版本:"))
        self.material_code_label.setText(_translate("ProductMainWindow", "XXXXXX"))
        self.label_15.setText(_translate("ProductMainWindow", "工具版本:"))
        self.tool_version_label.setText(_translate("ProductMainWindow", "XXXXX"))
        self.project_name_label.setText(_translate("ProductMainWindow", "XXXXXX"))
        self.label_12.setText(_translate("ProductMainWindow", "项目名称:"))
        self.label_8.setText(_translate("ProductMainWindow", "MES工单:"))
        self.order_num_label.setText(_translate("ProductMainWindow", "XXXXXX"))
        self.groupBox_2.setTitle(_translate("ProductMainWindow", "工位信息"))
        self.label_2.setText(_translate("ProductMainWindow", "工位类型："))
        self.label_5.setText(_translate("ProductMainWindow", "工位流程："))
        self.label_10.setText(_translate("ProductMainWindow", "CMW500地址："))
        self.label_11.setText(_translate("ProductMainWindow", "ADC校准电源地址："))
        self.station_type_label.setText(_translate("ProductMainWindow", "XXXXXX"))
        self.station_flow_label.setText(_translate("ProductMainWindow", "XXXXXXXXXXX"))
        self.dc_address_label.setText(_translate("ProductMainWindow", "XXXXXXX"))
        self.cmw_addr_label.setText(_translate("ProductMainWindow", "XXXXXX"))
        self.label_3.setText(_translate("ProductMainWindow", "工位编号："))
        self.station_num_label.setText(_translate("ProductMainWindow", "XXX"))
        self.label_4.setText(_translate("ProductMainWindow", "上传统计："))
        self.factory_mes_res_label.setText(_translate("ProductMainWindow", "成功: 0   失败：0"))
        self.linenum_txt_label.setText(_translate("ProductMainWindow", "线体编号："))
        self.line_num_label.setText(_translate("ProductMainWindow", "XXX"))
        self.product_info_gbox.setTitle(_translate("ProductMainWindow", "生产信息"))
        self.label_6.setText(_translate("ProductMainWindow", "当前IMEI："))
        self.res_bg_label.setText(_translate("ProductMainWindow", "等待"))
        self.elapsed_time_label.setText(_translate("ProductMainWindow", "0"))
        self.label_7.setText(_translate("ProductMainWindow", "成功总数:"))
        self.label_16.setText(_translate("ProductMainWindow", "失败总数:"))
        self.success_total_label.setText(_translate("ProductMainWindow", "0"))
        self.false_total_label.setText(_translate("ProductMainWindow", "0"))
        self.label_18.setText(_translate("ProductMainWindow", "LTE失败:"))
        self.label_19.setText(_translate("ProductMainWindow", "GSM失败:"))
        self.label_20.setText(_translate("ProductMainWindow", "ADC失败:"))
        self.label_21.setText(_translate("ProductMainWindow", "其它失败:"))
        self.lte_false_label.setText(_translate("ProductMainWindow", "0"))
        self.gsm_false_label.setText(_translate("ProductMainWindow", "0"))
        self.adc_false_label.setText(_translate("ProductMainWindow", "0"))
        self.other_false_label.setText(_translate("ProductMainWindow", "0"))
        self.label_22.setText(_translate("ProductMainWindow", "IMEI失败:"))
        self.imei_false_label.setText(_translate("ProductMainWindow", "0"))
        self.label_23.setText(_translate("ProductMainWindow", "MES失败:"))
        self.mes_false_label.setText(_translate("ProductMainWindow", "0"))
        self.groupBox_4.setTitle(_translate("ProductMainWindow", "当前信息"))
        self.label_9.setText(_translate("ProductMainWindow", "IMEI输入："))
        self.menu.setTitle(_translate("ProductMainWindow", "配置"))
        self.menu_2.setTitle(_translate("ProductMainWindow", "软件更新"))
        self.lossset_config_action.setText(_translate("ProductMainWindow", "线损配置"))
        self.action_2.setText(_translate("ProductMainWindow", "软件版本"))
        self.app_update.setText(_translate("ProductMainWindow", "版本列表"))
        self.app_update_action.setText(_translate("ProductMainWindow", "版本列表"))

