# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_config_load.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_toolConfigDialog(object):
    def setupUi(self, toolConfigDialog):
        toolConfigDialog.setObjectName("toolConfigDialog")
        toolConfigDialog.resize(745, 293)
        self.OK_btn = QtWidgets.QPushButton(toolConfigDialog)
        self.OK_btn.setGeometry(QtCore.QRect(320, 220, 111, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.OK_btn.setFont(font)
        self.OK_btn.setObjectName("OK_btn")
        self.download_1_progressbar = QtWidgets.QProgressBar(toolConfigDialog)
        self.download_1_progressbar.setGeometry(QtCore.QRect(180, 100, 541, 31))
        self.download_1_progressbar.setProperty("value", 0)
        self.download_1_progressbar.setObjectName("download_1_progressbar")
        self.dl_label_1 = QtWidgets.QLabel(toolConfigDialog)
        self.dl_label_1.setGeometry(QtCore.QRect(70, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.dl_label_1.setFont(font)
        self.dl_label_1.setObjectName("dl_label_1")
        self.download_2_progressbar = QtWidgets.QProgressBar(toolConfigDialog)
        self.download_2_progressbar.setGeometry(QtCore.QRect(180, 140, 541, 31))
        self.download_2_progressbar.setProperty("value", 0)
        self.download_2_progressbar.setObjectName("download_2_progressbar")
        self.dl_label_2 = QtWidgets.QLabel(toolConfigDialog)
        self.dl_label_2.setGeometry(QtCore.QRect(60, 134, 111, 41))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.dl_label_2.setFont(font)
        self.dl_label_2.setObjectName("dl_label_2")
        self.download_3_progressbar = QtWidgets.QProgressBar(toolConfigDialog)
        self.download_3_progressbar.setGeometry(QtCore.QRect(180, 180, 541, 31))
        self.download_3_progressbar.setProperty("value", 0)
        self.download_3_progressbar.setObjectName("download_3_progressbar")
        self.dl_label_3 = QtWidgets.QLabel(toolConfigDialog)
        self.dl_label_3.setGeometry(QtCore.QRect(60, 166, 111, 51))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.dl_label_3.setFont(font)
        self.dl_label_3.setObjectName("dl_label_3")

        self.retranslateUi(toolConfigDialog)
        QtCore.QMetaObject.connectSlotsByName(toolConfigDialog)

    def retranslateUi(self, toolConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        toolConfigDialog.setWindowTitle(_translate("toolConfigDialog", "工具配置和测试项目选择"))
        self.OK_btn.setText(_translate("toolConfigDialog", "确认"))
        self.dl_label_1.setText(_translate("toolConfigDialog", "DB下载:"))
        self.dl_label_2.setText(_translate("toolConfigDialog", "脚本下载:"))
        self.dl_label_3.setText(_translate("toolConfigDialog", "MMPT下载:"))
