# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_config.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_toolConfigDialog(object):
    def setupUi(self, toolConfigDialog):
        toolConfigDialog.setObjectName("toolConfigDialog")
        toolConfigDialog.resize(745, 633)
        self.label = QtWidgets.QLabel(toolConfigDialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(toolConfigDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 91, 21))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(toolConfigDialog)
        self.label_3.setGeometry(QtCore.QRect(40, 102, 161, 21))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(toolConfigDialog)
        self.label_4.setGeometry(QtCore.QRect(40, 140, 211, 21))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.mmpt_slot_total_cbox = QtWidgets.QComboBox(toolConfigDialog)
        self.mmpt_slot_total_cbox.setGeometry(QtCore.QRect(140, 20, 121, 31))
        self.mmpt_slot_total_cbox.setObjectName("mmpt_slot_total_cbox")
        self.work_type_cbox = QtWidgets.QComboBox(toolConfigDialog)
        self.work_type_cbox.setGeometry(QtCore.QRect(140, 60, 101, 31))
        self.work_type_cbox.setObjectName("work_type_cbox")
        self.cmw_slot_cbox = QtWidgets.QComboBox(toolConfigDialog)
        self.cmw_slot_cbox.setGeometry(QtCore.QRect(450, 100, 61, 31))
        self.cmw_slot_cbox.setObjectName("cmw_slot_cbox")
        self.gpib_addr_cbox = QtWidgets.QComboBox(toolConfigDialog)
        self.gpib_addr_cbox.setGeometry(QtCore.QRect(260, 140, 61, 31))
        self.gpib_addr_cbox.setObjectName("gpib_addr_cbox")
        self.dc_source_ch_cbox = QtWidgets.QComboBox(toolConfigDialog)
        self.dc_source_ch_cbox.setGeometry(QtCore.QRect(619, 142, 81, 31))
        self.dc_source_ch_cbox.setObjectName("dc_source_ch_cbox")
        self.instr_cbox = QtWidgets.QComboBox(toolConfigDialog)
        self.instr_cbox.setGeometry(QtCore.QRect(360, 140, 61, 31))
        self.instr_cbox.setObjectName("instr_cbox")
        self.label_5 = QtWidgets.QLabel(toolConfigDialog)
        self.label_5.setGeometry(QtCore.QRect(330, 140, 21, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(toolConfigDialog)
        self.label_6.setGeometry(QtCore.QRect(430, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(toolConfigDialog)
        self.label_7.setGeometry(QtCore.QRect(529, 141, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.dc_test_btn = QtWidgets.QPushButton(toolConfigDialog)
        self.dc_test_btn.setGeometry(QtCore.QRect(580, 180, 71, 41))
        self.dc_test_btn.setObjectName("dc_test_btn")
        self.cal_groupBox = QtWidgets.QGroupBox(toolConfigDialog)
        self.cal_groupBox.setGeometry(QtCore.QRect(20, 210, 241, 231))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.cal_groupBox.setFont(font)
        self.cal_groupBox.setObjectName("cal_groupBox")
        self.cal_lte_check = QtWidgets.QCheckBox(self.cal_groupBox)
        self.cal_lte_check.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.cal_lte_check.setObjectName("cal_lte_check")
        self.cal_gsm_check = QtWidgets.QCheckBox(self.cal_groupBox)
        self.cal_gsm_check.setGeometry(QtCore.QRect(20, 52, 91, 21))
        self.cal_gsm_check.setObjectName("cal_gsm_check")
        self.cal_adc_check = QtWidgets.QCheckBox(self.cal_groupBox)
        self.cal_adc_check.setGeometry(QtCore.QRect(20, 74, 91, 21))
        self.cal_adc_check.setObjectName("cal_adc_check")
        self.cal_imei_check = QtWidgets.QCheckBox(self.cal_groupBox)
        self.cal_imei_check.setGeometry(QtCore.QRect(20, 100, 111, 21))
        self.cal_imei_check.setObjectName("cal_imei_check")
        self.cal_auth_check = QtWidgets.QCheckBox(self.cal_groupBox)
        self.cal_auth_check.setGeometry(QtCore.QRect(20, 155, 101, 21))
        self.cal_auth_check.setObjectName("cal_auth_check")
        self.cal_sn_check = QtWidgets.QCheckBox(self.cal_groupBox)
        self.cal_sn_check.setGeometry(QtCore.QRect(20, 128, 121, 21))
        self.cal_sn_check.setObjectName("cal_sn_check")
        self.nst_groupBox = QtWidgets.QGroupBox(toolConfigDialog)
        self.nst_groupBox.setGeometry(QtCore.QRect(270, 210, 241, 231))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.nst_groupBox.setFont(font)
        self.nst_groupBox.setObjectName("nst_groupBox")
        self.nst_lte_check = QtWidgets.QCheckBox(self.nst_groupBox)
        self.nst_lte_check.setGeometry(QtCore.QRect(20, 30, 81, 21))
        self.nst_lte_check.setObjectName("nst_lte_check")
        self.nst_gsm_check = QtWidgets.QCheckBox(self.nst_groupBox)
        self.nst_gsm_check.setGeometry(QtCore.QRect(20, 53, 91, 21))
        self.nst_gsm_check.setObjectName("nst_gsm_check")
        self.nst_adc_check = QtWidgets.QCheckBox(self.nst_groupBox)
        self.nst_adc_check.setGeometry(QtCore.QRect(20, 77, 101, 21))
        self.nst_adc_check.setObjectName("nst_adc_check")
        self.nst_imei_check = QtWidgets.QCheckBox(self.nst_groupBox)
        self.nst_imei_check.setGeometry(QtCore.QRect(20, 100, 111, 21))
        self.nst_imei_check.setObjectName("nst_imei_check")
        self.nst_auth_check = QtWidgets.QCheckBox(self.nst_groupBox)
        self.nst_auth_check.setGeometry(QtCore.QRect(20, 147, 101, 31))
        self.nst_auth_check.setObjectName("nst_auth_check")
        self.nst_sn_check = QtWidgets.QCheckBox(self.nst_groupBox)
        self.nst_sn_check.setGeometry(QtCore.QRect(20, 120, 131, 31))
        self.nst_sn_check.setObjectName("nst_sn_check")
        self.cal_auth_check_2 = QtWidgets.QCheckBox(self.nst_groupBox)
        self.cal_auth_check_2.setEnabled(False)
        self.cal_auth_check_2.setGeometry(QtCore.QRect(20, 170, 101, 31))
        self.cal_auth_check_2.setChecked(True)
        self.cal_auth_check_2.setObjectName("cal_auth_check_2")
        self.cal_auth_check_3 = QtWidgets.QCheckBox(self.nst_groupBox)
        self.cal_auth_check_3.setEnabled(False)
        self.cal_auth_check_3.setGeometry(QtCore.QRect(20, 190, 101, 31))
        self.cal_auth_check_3.setChecked(True)
        self.cal_auth_check_3.setObjectName("cal_auth_check_3")
        self.OK_btn = QtWidgets.QPushButton(toolConfigDialog)
        self.OK_btn.setGeometry(QtCore.QRect(280, 570, 111, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.OK_btn.setFont(font)
        self.OK_btn.setObjectName("OK_btn")
        self.cmw_ip_edit = QtWidgets.QLineEdit(toolConfigDialog)
        self.cmw_ip_edit.setGeometry(QtCore.QRect(200, 100, 171, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.cmw_ip_edit.setFont(font)
        self.cmw_ip_edit.setObjectName("cmw_ip_edit")
        self.label_9 = QtWidgets.QLabel(toolConfigDialog)
        self.label_9.setGeometry(QtCore.QRect(400, 100, 51, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(toolConfigDialog)
        self.label_10.setGeometry(QtCore.QRect(270, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.station_num_cbox = QtWidgets.QComboBox(toolConfigDialog)
        self.station_num_cbox.setGeometry(QtCore.QRect(380, 60, 71, 31))
        self.station_num_cbox.setObjectName("station_num_cbox")
        self.download_1_progressbar = QtWidgets.QProgressBar(toolConfigDialog)
        self.download_1_progressbar.setGeometry(QtCore.QRect(140, 450, 541, 31))
        self.download_1_progressbar.setProperty("value", 0)
        self.download_1_progressbar.setObjectName("download_1_progressbar")
        self.dl_label_1 = QtWidgets.QLabel(toolConfigDialog)
        self.dl_label_1.setGeometry(QtCore.QRect(30, 450, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.dl_label_1.setFont(font)
        self.dl_label_1.setObjectName("dl_label_1")
        self.download_2_progressbar = QtWidgets.QProgressBar(toolConfigDialog)
        self.download_2_progressbar.setGeometry(QtCore.QRect(140, 490, 541, 31))
        self.download_2_progressbar.setProperty("value", 0)
        self.download_2_progressbar.setObjectName("download_2_progressbar")
        self.dl_label_2 = QtWidgets.QLabel(toolConfigDialog)
        self.dl_label_2.setGeometry(QtCore.QRect(20, 484, 111, 41))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.dl_label_2.setFont(font)
        self.dl_label_2.setObjectName("dl_label_2")
        self.reset_btn = QtWidgets.QPushButton(toolConfigDialog)
        self.reset_btn.setGeometry(QtCore.QRect(400, 10, 91, 41))
        self.reset_btn.setObjectName("reset_btn")
        self.download_3_progressbar = QtWidgets.QProgressBar(toolConfigDialog)
        self.download_3_progressbar.setGeometry(QtCore.QRect(140, 530, 541, 31))
        self.download_3_progressbar.setProperty("value", 0)
        self.download_3_progressbar.setObjectName("download_3_progressbar")
        self.dl_label_3 = QtWidgets.QLabel(toolConfigDialog)
        self.dl_label_3.setGeometry(QtCore.QRect(20, 516, 111, 51))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.dl_label_3.setFont(font)
        self.dl_label_3.setObjectName("dl_label_3")
        self.line_num_label = QtWidgets.QLabel(toolConfigDialog)
        self.line_num_label.setGeometry(QtCore.QRect(480, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.line_num_label.setFont(font)
        self.line_num_label.setObjectName("line_num_label")
        self.line_num_cbox = QtWidgets.QComboBox(toolConfigDialog)
        self.line_num_cbox.setGeometry(QtCore.QRect(580, 60, 81, 31))
        self.line_num_cbox.setObjectName("line_num_cbox")
        self.label_8 = QtWidgets.QLabel(toolConfigDialog)
        self.label_8.setGeometry(QtCore.QRect(40, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.adc_detect_label = QtWidgets.QLabel(toolConfigDialog)
        self.adc_detect_label.setGeometry(QtCore.QRect(180, 170, 81, 31))
        self.adc_detect_label.setAlignment(QtCore.Qt.AlignCenter)
        self.adc_detect_label.setObjectName("adc_detect_label")

        self.retranslateUi(toolConfigDialog)
        QtCore.QMetaObject.connectSlotsByName(toolConfigDialog)

    def retranslateUi(self, toolConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        toolConfigDialog.setWindowTitle(_translate("toolConfigDialog", "工具配置和测试项目选择"))
        self.label.setText(_translate("toolConfigDialog", "同测数量："))
        self.label_2.setText(_translate("toolConfigDialog", "工位类型："))
        self.label_3.setText(_translate("toolConfigDialog", "CMW500地址： IP"))
        self.label_4.setText(_translate("toolConfigDialog", "ADC校准电源地址：GPIB"))
        self.label_5.setText(_translate("toolConfigDialog", "::"))
        self.label_6.setText(_translate("toolConfigDialog", "::INSTR"))
        self.label_7.setText(_translate("toolConfigDialog", "电源通道"))
        self.dc_test_btn.setText(_translate("toolConfigDialog", "电源测试"))
        self.cal_groupBox.setTitle(_translate("toolConfigDialog", "校准项目选择"))
        self.cal_lte_check.setText(_translate("toolConfigDialog", "LTE"))
        self.cal_gsm_check.setText(_translate("toolConfigDialog", "GSM"))
        self.cal_adc_check.setText(_translate("toolConfigDialog", "ADC"))
        self.cal_imei_check.setText(_translate("toolConfigDialog", "IMEI写入"))
        self.cal_auth_check.setText(_translate("toolConfigDialog", "设备激活"))
        self.cal_sn_check.setText(_translate("toolConfigDialog", "模组序列号"))
        self.nst_groupBox.setTitle(_translate("toolConfigDialog", "综测项目选择"))
        self.nst_lte_check.setText(_translate("toolConfigDialog", "LTE"))
        self.nst_gsm_check.setText(_translate("toolConfigDialog", "GSM"))
        self.nst_adc_check.setText(_translate("toolConfigDialog", "ADC"))
        self.nst_imei_check.setText(_translate("toolConfigDialog", "IMEI测试"))
        self.nst_auth_check.setText(_translate("toolConfigDialog", "设备激活"))
        self.nst_sn_check.setText(_translate("toolConfigDialog", "模组序列号"))
        self.cal_auth_check_2.setText(_translate("toolConfigDialog", "IO测试"))
        self.cal_auth_check_3.setText(_translate("toolConfigDialog", "功耗测试"))
        self.OK_btn.setText(_translate("toolConfigDialog", "确认"))
        self.cmw_ip_edit.setText(_translate("toolConfigDialog", "172.22.1.3"))
        self.label_9.setText(_translate("toolConfigDialog", "SLOT"))
        self.label_10.setText(_translate("toolConfigDialog", "工位编号："))
        self.dl_label_1.setText(_translate("toolConfigDialog", "DB下载:"))
        self.dl_label_2.setText(_translate("toolConfigDialog", "脚本下载:"))
        self.reset_btn.setText(_translate("toolConfigDialog", "重新配置"))
        self.dl_label_3.setText(_translate("toolConfigDialog", "MMPT下载:"))
        self.line_num_label.setText(_translate("toolConfigDialog", "线体编号："))
        self.label_8.setText(_translate("toolConfigDialog", "电源测试模块"))
        self.adc_detect_label.setText(_translate("toolConfigDialog", "未连接"))

